# Generated by Django 2.0.5 on 2018-06-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyConverter',
        ),
        migrations.DeleteModel(
            name='CustomerBankaccount',
        ),
        migrations.DeleteModel(
            name='LoanCalculator',
        ),
        migrations.DeleteModel(
            name='Registercustomer',
        ),
        migrations.DeleteModel(
            name='Registercustomertranscations',
        ),
    ]
