# Generated by Django 2.0.5 on 2018-06-05 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userprofile',
            new_name='Myaccount',
        ),
    ]
